services:
  simple-nodejs-app:
    image: simple-nodejs-app:latest
    ports:
      - "8080:3000"
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - webnet

networks:
  webnet:
